In [1]:
import numpy as np

In [41]:
a = [1, 2, 3]
b = np.array([1, 2, 3])

print(a)
print(b)

print(type(a))
print(type(b))

print(b.shape)

[1, 2, 3]
[1 2 3]
<class 'list'>
<class 'numpy.ndarray'>
(3,)


In [42]:
c = np.array([ [1, 2, 3], [4, 5, 6] ])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [55]:
n1 = np.array([1, 2, 3])
n2 = np.array([4, 5, 6])

print(n1 + n2)
print(n1 - n2)
print(n1 * n2)
print(n1 / n2)
print(n2 % n1)
print(n1.dot(n2)) # 내적

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 1 0]
32


In [26]:
print(n2) # [4 5 6]
print(n2 + 5)
print(n2 - 5)
print(n2 * 5)
print(n2 / 5)
print(n2 % 5)

[4 5 6]
[ 9 10 11]
[-1  0  1]
[20 25 30]
[0.8 1.  1.2]
[4 0 1]


In [44]:
d = np.array([1, 2, 3, 4, 5, 9, 10])
print(np.max(d))
print(np.min(d))
print(np.average(d))
print(np.median(d))
print(np.var(d))
print(np.std(d))

10
1
4.857142857142857
4.0
10.122448979591837
3.1815796359028696


In [39]:
print(d)
# print(d[d 중에 4 이상만 찾아줘])
print(d[d >= 4])

[ 1  2  3  4  5  9 10]
[ 4  5  9 10]


In [52]:
print( np.ones((2, 3)) )
print( np.zeros((2, 3)) )

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [53]:
print( np.random.random((2, 3)) )

[[0.14153227 0.63839318 0.75291669]
 [0.32450458 0.81512488 0.266525  ]]


# 판다스

[참고](https://doorbw.tistory.com/172)

In [57]:
import pandas as pd

In [94]:
a1 = np.array( [[1,2,3], [4,5,6]] )
p1 = pd.DataFrame(a1)

p1

0  1  2
0  1  2  3
1  4  5  6

In [93]:
a2 = {"서울": ["마포", "강남", "서대문"], "경기": ["의정부", "성남", "부천"]}
p2 = pd.DataFrame(a2)

p2

서울   경기
0   마포  의정부
1   강남   성남
2  서대문   부천

In [98]:
a3 = [1, 3, 5, 7]
p3 = pd.DataFrame(data=a3)

print(p3)
print('---------')

a3 = [1, 3, 5, 7]
p3 = pd.DataFrame(data=a3, index=["hi", "my", "name", "is"])

print(p3)
print('---------')

a3 = [1, 3, 5, 7]
p3 = pd.DataFrame(data=a3, index=["hi", "my", "name", "is"], columns=['kor'])

print(p3)
print('---------')

p3

   0
0  1
1  3
2  5
3  7
---------
      0
hi    1
my    3
name  5
is    7
---------
      kor
hi      1
my      3
name    5
is      7
---------


kor
hi      1
my      3
name    5
is      7

In [114]:
s1 = pd.Series([1, 2, 3])
print(s1)

pd.DataFrame(s1)

0    1
1    2
2    3
dtype: int64


0
0  1
1  2
2  3

In [161]:
s1.name = 'Test111'
print(pd.DataFrame(s1))

    Test111
ko      123
jp       10


In [127]:
s2 = pd.Series({ "ko": 4000, "jp": 10000 })
s2.index = ['KRW', 'JPY']
s2

KRW     4000
JPY    10000
dtype: int64

In [130]:
# Data Frame 정의하기
# 이전에 DataFrame에 들어갈 데이터를 정의해주어야 하는데,
# 이는 python의 dictionary 또는 numpy의 array로 정의할 수 있다.
data = {'name': ['Beomwoo', 'Beomwoo', 'Beomwoo', 'Kim', 'Park'],
        'year': [2013, 2014, 2015, 2016, 2015],
        'points': [1.5, 1.7, 3.6, 2.4, 2.9]}
df = pd.DataFrame(data)
df

name  year  points
0  Beomwoo  2013     1.5
1  Beomwoo  2014     1.7
2  Beomwoo  2015     3.6
3      Kim  2016     2.4
4     Park  2015     2.9

In [135]:
df.values #numpy

array([['Beomwoo', 2013, 1.5],
       ['Beomwoo', 2014, 1.7],
       ['Beomwoo', 2015, 3.6],
       ['Kim', 2016, 2.4],
       ['Park', 2015, 2.9]], dtype=object)

In [143]:
df.index.name = 'Num'
df.columns.name = 'Info'
df

Info        a     b    c
Num                     
5     Beomwoo  2013  1.5
6     Beomwoo  2014  1.7
3     Beomwoo  2015  3.6
2         Kim  2016  2.4
1        Park  2015  2.9

In [144]:
df.columns = ['a', 'b', 'c']
df.index = [5, 6, 3, 2, 1]
df

a     b    c
5  Beomwoo  2013  1.5
6  Beomwoo  2014  1.7
3  Beomwoo  2015  3.6
2      Kim  2016  2.4
1     Park  2015  2.9

In [145]:
df.index.name = 'Num'
df.columns.name = 'Info'
df

Info        a     b    c
Num                     
5     Beomwoo  2013  1.5
6     Beomwoo  2014  1.7
3     Beomwoo  2015  3.6
2         Kim  2016  2.4
1        Park  2015  2.9

In [147]:
df2 = pd.DataFrame(data, columns=['year', 'name', 'points', 'penalty'],
                  index=['one', 'two', 'three', 'four', 'five'])
df2

year     name  points penalty
one    2013  Beomwoo     1.5     NaN
two    2014  Beomwoo     1.7     NaN
three  2015  Beomwoo     3.6     NaN
four   2016      Kim     2.4     NaN
five   2015     Park     2.9     NaN

In [148]:
df2.describe()

year    points
count     5.000000  5.000000
mean   2014.600000  2.420000
std       1.140175  0.864292
min    2013.000000  1.500000
25%    2014.000000  1.700000
50%    2015.000000  2.400000
75%    2015.000000  2.900000
max    2016.000000  3.600000

# DataFrame Indexing

In [152]:
data = {"names": ["Kilho", "Kilho", "Kilho", "Charles", "Charles"],
           "year": [2014, 2015, 2016, 2015, 2016],
           "points": [1.5, 1.7, 3.6, 2.4, 2.9]}
df = pd.DataFrame(data, columns=["year", "names", "points", "penalty"],
                          index=["one", "two", "three", "four", "five"])
df

year    names  points penalty
one    2014    Kilho     1.5     NaN
two    2015    Kilho     1.7     NaN
three  2016    Kilho     3.6     NaN
four   2015  Charles     2.4     NaN
five   2016  Charles     2.9     NaN

In [164]:
df['year']

one      2014
two      2015
three    2016
four     2015
five     2016
Name: year, dtype: int64

In [165]:
df[['year', 'points']]

year  points
one    2014     1.5
two    2015     1.7
three  2016     3.6
four   2015     2.4
five   2016     2.9

In [170]:
df['penalty'] = 0.1
df['penalty'] = [0.5, 1, 2, 3, 4]
df

year    names  points  penalty
one    2014    Kilho     1.5      0.5
two    2015    Kilho     1.7      1.0
three  2016    Kilho     3.6      2.0
four   2015  Charles     2.4      3.0
five   2016  Charles     2.9      4.0

In [175]:
df['etc'] = range(5)
df['etc'] = np.random.random(5)
df

year    names  points  penalty       etc
one    2014    Kilho     1.5      0.5  0.075828
two    2015    Kilho     1.7      1.0  0.812285
three  2016    Kilho     3.6      2.0  0.745917
four   2015  Charles     2.4      3.0  0.181146
five   2016  Charles     2.9      4.0  0.792379

{'bb': 2}

In [211]:
data = {"names": ["Kilho", "Kilho", "Kilho", "Charles", "Charles"],
           "year": [2014, 2015, 2016, 2015, 2016],
           "points": [1.5, 1.7, 3.6, 2.4, 2.9]}
df = pd.DataFrame(data, columns=["year", "names", "points", "penalty"],
                          index=["one", "two", "three", "four", "five"])
df

year    names  points penalty
one    2014    Kilho     1.5     NaN
two    2015    Kilho     1.7     NaN
three  2016    Kilho     3.6     NaN
four   2015  Charles     2.4     NaN
five   2016  Charles     2.9     NaN

In [271]:
names = pd.Series(["Kilho", "Kilho", "Kilho", "Charles", "Charles"])
year = pd.Series([2014, 2015, 2016, 2015, 2016])
points = pd.Series([1.5, 1.7, 3.6, 2.4, 2.9])

d = pd.DataFrame([], columns=["year", "names", "points"],
                          index=['one', 'two','three', 'four', 'five'])

d['year']

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
Name: year, dtype: object

In [250]:
d.iloc[:,0] = year

In [251]:
d

year names points
0  2014   NaN    NaN
1  2015   NaN    NaN
2  2016   NaN    NaN
3  2015   NaN    NaN
4  2016   NaN    NaN

In [256]:
row = pd.Series({ 'year': 2014, 'names': 'asdf', 'points': 1.3 })
row

year      2014
names     asdf
points     1.3
dtype: object

In [257]:
d.iloc[0] = row

In [258]:
d

year names points
0  2014.0  asdf    1.3
1  2015.0   NaN    NaN
2  2016.0   NaN    NaN
3  2015.0   NaN    NaN
4  2016.0   NaN    NaN

In [273]:
d.loc[:, 'year'] = [2010, 'gg', 10, 3, 5]
# d.year = pd.Series([2010, 'gg', 10, 3])
d

year names points
one    2010   NaN    NaN
two      gg   NaN    NaN
three    10   NaN    NaN
four      3   NaN    NaN
five      5   NaN    NaN

In [284]:
d2 = pd.DataFrame(data)
d2

names  year  points
0    Kilho  2014     1.5
1    Kilho  2015     1.7
2    Kilho  2016     3.6
3  Charles  2015     2.4
4  Charles  2016     2.9

In [292]:
d.drop('one', axis=0)

year names points
two     gg   NaN    NaN
three   10   NaN    NaN
four     3   NaN    NaN
five     5   NaN    NaN

In [297]:
k = np.array([[1,2,3], [4,5,6]])
k

array([[1, 2, 3],
       [4, 5, 6]])

In [299]:
print(k.sum(axis=0))
print(k.sum(axis=1))

[5 7 9]
[ 6 15]
